[profile.default]
libs = ["lib"]
optimizer = true
optimizer_runs = 10000
out = "out"
solc = "0.8.30"
src = "src"
via_ir = true
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
